# QuickGPT Netlify Configuration
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

# Environment variables (set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Function configuration
[functions]
  # Functions will use default timeout (10s)

# Redirect rules for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/prism.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/prism.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Function-specific headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Development settings
[dev]
  command = "echo 'No dev server needed'"
  port = 8888
  publish = "public"
